# Project 1

## Author: Yefrid Cordoba

## ST - 554 Big data analysis

## Part I

In this part, a class`SparkDataCheck` was created to perform a data check for the airquality data from the UC Irvine ML repo, including different ways to create instances for the class, checking that the some numeric variable falls in a user defined range, or showing frequencies for 1 or 2 non-numeric variables.\
The development of this class is important to add to our tools that we are going to use in the end of the course for data that is obtained overtime.

First we initialize the Spark session

In [242]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('my_app').config("spark.sql.ansi.enabled", "false").getOrCreate()

Then, the module that contains the class is imported into the session

In [243]:
import Project2_class_YC
import pandas as pd

In [244]:
import importlib
importlib.reload(Project2_class_YC)

Now, an instance for the class is created from the csv file, which is saved ina folder called `Data`, relative to my working directory.

In [245]:
air_data = Project2_class_YC.SparkDataCheck.createfrom_csv(spark, 'Data/air.csv')

It is necessary to rename the columns that have notation that can be undertand in a different way by the program (e.g., `'PT08.S1(CO)'` to `'S1(CO)'` )

In [246]:
air_data.df = air_data.df.withColumnsRenamed({\
                                              'PT08.S1(CO)':'S1(CO)', 'PT08.S2(NMHC)':'S2(NMHC)', 'PT08.S3(NOx)':'S3(NOx)', \
                                              'PT08.S4(NO2)': 'S4(NO2)', 'PT08.S5(O3)':'S5(O3)'})

In [247]:
air_data.df.show(10)

+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+
|_c0|     Date|               Time|CO(GT)|S1(CO)|NMHC(GT)|C6H6(GT)|S2(NMHC)|NOx(GT)|S3(NOx)|NO2(GT)|S4(NO2)|S5(O3)|   T|  RH|    AH|
+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+
|  0|3/10/2004|2026-03-24 18:00:00|   2.6|  1360|     150|    11.9|    1046|    166|   1056|    113|   1692|  1268|13.6|48.9|0.7578|
|  1|3/10/2004|2026-03-24 19:00:00|   2.0|  1292|     112|     9.4|     955|    103|   1174|     92|   1559|   972|13.3|47.7|0.7255|
|  2|3/10/2004|2026-03-24 20:00:00|   2.2|  1402|      88|     9.0|     939|    131|   1140|    114|   1555|  1074|11.9|54.0|0.7502|
|  3|3/10/2004|2026-03-24 21:00:00|   2.2|  1376|      80|     9.2|     948|    172|   1092|    122|   1584|  1203|11.0|60.0|0.7867|
|  4|3/10/2004|2026-03-24 22:00:00|   1.6|  1272|      51|     6.5|     836|    131|   1205|    116|   1490|  1110|11.2|59.6|0.7888|
|  5|3/10/2004|2026-03-24 23:00:00|   1.2|  1197|      38|     4.7|     750|     89|   1337|     96|   1393|   949|11.2|59.2|0.7848|
|  6|3/11/2004|2026-03-24 00:00:00|   1.2|  1185|      31|     3.6|     690|     62|   1462|     77|   1333|   733|11.3|56.8|0.7603|
|  7|3/11/2004|2026-03-24 01:00:00|   1.0|  1136|      31|     3.3|     672|     62|   1453|     76|   1333|   730|10.7|60.0|0.7702|
|  8|3/11/2004|2026-03-24 02:00:00|   0.9|  1094|      24|     2.3|     609|     45|   1579|     60|   1276|   620|10.7|59.7|0.7648|
|  9|3/11/2004|2026-03-24 03:00:00|   0.6|  1010|      19|     1.7|     561|   -200|   1705|   -200|   1235|   501|10.3|60.2|0.7517|
+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+
only showing top 10 rows

26/03/24 19:27:38 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-yacordob@ncsu.edu/Data/air.csv

Showinf the first 10 rows of the instance of the class created, from which the last row (index 9), contains missing values, which are shown as `-200` in the dataframe./
For that reason, it is necessary to replace those values in the dataframe using the method `df.replace()` to create the Null values recognizable by pySpark.

In [248]:
air_data.df = air_data.df.replace(-200, None)

Checking that the `-200` changed for `Null` (or None)in the dataframe.

In [249]:
air_data.df.show(10)

+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+
|_c0|     Date|               Time|CO(GT)|S1(CO)|NMHC(GT)|C6H6(GT)|S2(NMHC)|NOx(GT)|S3(NOx)|NO2(GT)|S4(NO2)|S5(O3)|   T|  RH|    AH|
+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+
|  0|3/10/2004|2026-03-24 18:00:00|   2.6|  1360|     150|    11.9|    1046|    166|   1056|    113|   1692|  1268|13.6|48.9|0.7578|
|  1|3/10/2004|2026-03-24 19:00:00|   2.0|  1292|     112|     9.4|     955|    103|   1174|     92|   1559|   972|13.3|47.7|0.7255|
|  2|3/10/2004|2026-03-24 20:00:00|   2.2|  1402|      88|     9.0|     939|    131|   1140|    114|   1555|  1074|11.9|54.0|0.7502|
|  3|3/10/2004|2026-03-24 21:00:00|   2.2|  1376|      80|     9.2|     948|    172|   1092|    122|   1584|  1203|11.0|60.0|0.7867|
|  4|3/10/2004|2026-03-24 22:00:00|   1.6|  1272|      51|     6.5|     836|    131|   1205|    116|   1490|  1110|11.2|59.6|0.7888|
|  5|3/10/2004|2026-03-24 23:00:00|   1.2|  1197|      38|     4.7|     750|     89|   1337|     96|   1393|   949|11.2|59.2|0.7848|
|  6|3/11/2004|2026-03-24 00:00:00|   1.2|  1185|      31|     3.6|     690|     62|   1462|     77|   1333|   733|11.3|56.8|0.7603|
|  7|3/11/2004|2026-03-24 01:00:00|   1.0|  1136|      31|     3.3|     672|     62|   1453|     76|   1333|   730|10.7|60.0|0.7702|
|  8|3/11/2004|2026-03-24 02:00:00|   0.9|  1094|      24|     2.3|     609|     45|   1579|     60|   1276|   620|10.7|59.7|0.7648|
|  9|3/11/2004|2026-03-24 03:00:00|   0.6|  1010|      19|     1.7|     561|   NULL|   1705|   NULL|   1235|   501|10.3|60.2|0.7517|
+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+
only showing top 10 rows

26/03/24 19:27:38 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-yacordob@ncsu.edu/Data/air.csv

### Examples of the class methods

#### When all bounds are included for a numeric variable

First we are going to check when it is numeric and both of the limits are included in the method ()which should work whitout exeptions

In [250]:
air_data.create_range_boolean('NO2(GT)', lower = 90, upper = 115)

DataFrame[_c0: int, Date: string, Time: timestamp, CO(GT): double, S1(CO): int, NMHC(GT): int, C6H6(GT): double, S2(NMHC): int, NOx(GT): int, S3(NOx): int, NO2(GT): int, S4(NO2): int, S5(O3): int, T: double, RH: double, AH: double, Is_in_range: boolean]

In [251]:
air_data.df.show(10)

+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+-----------+
|_c0|     Date|               Time|CO(GT)|S1(CO)|NMHC(GT)|C6H6(GT)|S2(NMHC)|NOx(GT)|S3(NOx)|NO2(GT)|S4(NO2)|S5(O3)|   T|  RH|    AH|Is_in_range|
+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+-----------+
|  0|3/10/2004|2026-03-24 18:00:00|   2.6|  1360|     150|    11.9|    1046|    166|   1056|    113|   1692|  1268|13.6|48.9|0.7578|       true|
|  1|3/10/2004|2026-03-24 19:00:00|   2.0|  1292|     112|     9.4|     955|    103|   1174|     92|   1559|   972|13.3|47.7|0.7255|       true|
|  2|3/10/2004|2026-03-24 20:00:00|   2.2|  1402|      88|     9.0|     939|    131|   1140|    114|   1555|  1074|11.9|54.0|0.7502|       true|
|  3|3/10/2004|2026-03-24 21:00:00|   2.2|  1376|      80|     9.2|     948|    172|   1092|    122|   1584|  1203|11.0|60.0|0.7867|      false|
|  4|3/10/2004|2026-03-24 22:00:00|   1.6|  1272|      51|     6.5|     836|    131|   1205|    116|   1490|  1110|11.2|59.6|0.7888|      false|
|  5|3/10/2004|2026-03-24 23:00:00|   1.2|  1197|      38|     4.7|     750|     89|   1337|     96|   1393|   949|11.2|59.2|0.7848|       true|
|  6|3/11/2004|2026-03-24 00:00:00|   1.2|  1185|      31|     3.6|     690|     62|   1462|     77|   1333|   733|11.3|56.8|0.7603|      false|
|  7|3/11/2004|2026-03-24 01:00:00|   1.0|  1136|      31|     3.3|     672|     62|   1453|     76|   1333|   730|10.7|60.0|0.7702|      false|
|  8|3/11/2004|2026-03-24 02:00:00|   0.9|  1094|      24|     2.3|     609|     45|   1579|     60|   1276|   620|10.7|59.7|0.7648|      false|
|  9|3/11/2004|2026-03-24 03:00:00|   0.6|  1010|      19|     1.7|     561|   NULL|   1705|   NULL|   1235|   501|10.3|60.2|0.7517|       NULL|
+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+-----------+
only showing top 10 rows

26/03/24 19:27:38 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-yacordob@ncsu.edu/Data/air.csv

It is clear that based on the range provided it included what it was supposed to, also the Null values were included as Null in the new column created.

#### When lower limit is missing

In this part we are going to check the code when lower bound is missing.

In [252]:
air_data.create_range_boolean('NO2(GT)', upper = 115)
air_data.df.show(10)

+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+-----------+
|_c0|     Date|               Time|CO(GT)|S1(CO)|NMHC(GT)|C6H6(GT)|S2(NMHC)|NOx(GT)|S3(NOx)|NO2(GT)|S4(NO2)|S5(O3)|   T|  RH|    AH|Is_in_range|
+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+-----------+
|  0|3/10/2004|2026-03-24 18:00:00|   2.6|  1360|     150|    11.9|    1046|    166|   1056|    113|   1692|  1268|13.6|48.9|0.7578|       true|
|  1|3/10/2004|2026-03-24 19:00:00|   2.0|  1292|     112|     9.4|     955|    103|   1174|     92|   1559|   972|13.3|47.7|0.7255|       true|
|  2|3/10/2004|2026-03-24 20:00:00|   2.2|  1402|      88|     9.0|     939|    131|   1140|    114|   1555|  1074|11.9|54.0|0.7502|       true|
|  3|3/10/2004|2026-03-24 21:00:00|   2.2|  1376|      80|     9.2|     948|    172|   1092|    122|   1584|  1203|11.0|60.0|0.7867|      false|
|  4|3/10/2004|2026-03-24 22:00:00|   1.6|  1272|      51|     6.5|     836|    131|   1205|    116|   1490|  1110|11.2|59.6|0.7888|      false|
|  5|3/10/2004|2026-03-24 23:00:00|   1.2|  1197|      38|     4.7|     750|     89|   1337|     96|   1393|   949|11.2|59.2|0.7848|       true|
|  6|3/11/2004|2026-03-24 00:00:00|   1.2|  1185|      31|     3.6|     690|     62|   1462|     77|   1333|   733|11.3|56.8|0.7603|       true|
|  7|3/11/2004|2026-03-24 01:00:00|   1.0|  1136|      31|     3.3|     672|     62|   1453|     76|   1333|   730|10.7|60.0|0.7702|       true|
|  8|3/11/2004|2026-03-24 02:00:00|   0.9|  1094|      24|     2.3|     609|     45|   1579|     60|   1276|   620|10.7|59.7|0.7648|       true|
|  9|3/11/2004|2026-03-24 03:00:00|   0.6|  1010|      19|     1.7|     561|   NULL|   1705|   NULL|   1235|   501|10.3|60.2|0.7517|       NULL|
+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+-----------+
only showing top 10 rows

26/03/24 19:27:38 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-yacordob@ncsu.edu/Data/air.csv

Of course the values that were below the lower limit previously now are included in the range.

#### When upper limit is missing

Now the upper limit is not going to be included in the method.

In [253]:
air_data.create_range_boolean('NO2(GT)', lower = 90)
air_data.df.show(10)

+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+-----------+
|_c0|     Date|               Time|CO(GT)|S1(CO)|NMHC(GT)|C6H6(GT)|S2(NMHC)|NOx(GT)|S3(NOx)|NO2(GT)|S4(NO2)|S5(O3)|   T|  RH|    AH|Is_in_range|
+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+-----------+
|  0|3/10/2004|2026-03-24 18:00:00|   2.6|  1360|     150|    11.9|    1046|    166|   1056|    113|   1692|  1268|13.6|48.9|0.7578|       true|
|  1|3/10/2004|2026-03-24 19:00:00|   2.0|  1292|     112|     9.4|     955|    103|   1174|     92|   1559|   972|13.3|47.7|0.7255|       true|
|  2|3/10/2004|2026-03-24 20:00:00|   2.2|  1402|      88|     9.0|     939|    131|   1140|    114|   1555|  1074|11.9|54.0|0.7502|       true|
|  3|3/10/2004|2026-03-24 21:00:00|   2.2|  1376|      80|     9.2|     948|    172|   1092|    122|   1584|  1203|11.0|60.0|0.7867|       true|
|  4|3/10/2004|2026-03-24 22:00:00|   1.6|  1272|      51|     6.5|     836|    131|   1205|    116|   1490|  1110|11.2|59.6|0.7888|       true|
|  5|3/10/2004|2026-03-24 23:00:00|   1.2|  1197|      38|     4.7|     750|     89|   1337|     96|   1393|   949|11.2|59.2|0.7848|       true|
|  6|3/11/2004|2026-03-24 00:00:00|   1.2|  1185|      31|     3.6|     690|     62|   1462|     77|   1333|   733|11.3|56.8|0.7603|      false|
|  7|3/11/2004|2026-03-24 01:00:00|   1.0|  1136|      31|     3.3|     672|     62|   1453|     76|   1333|   730|10.7|60.0|0.7702|      false|
|  8|3/11/2004|2026-03-24 02:00:00|   0.9|  1094|      24|     2.3|     609|     45|   1579|     60|   1276|   620|10.7|59.7|0.7648|      false|
|  9|3/11/2004|2026-03-24 03:00:00|   0.6|  1010|      19|     1.7|     561|   NULL|   1705|   NULL|   1235|   501|10.3|60.2|0.7517|       NULL|
+---+---------+-------------------+------+------+--------+--------+--------+-------+-------+-------+-------+------+----+----+------+-----------+
only showing top 10 rows

26/03/24 19:27:38 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-yacordob@ncsu.edu/Data/air.csv

And all the values that are above the lower limit are included now.

#### Non-numeric column is added

The column date now is going to be the input for our method to test the printed message

In [254]:
air_data.create_range_boolean('Date', lower = 90)

The column Date is not a numeric column

DataFrame[_c0: int, Date: string, Time: timestamp, CO(GT): double, S1(CO): int, NMHC(GT): int, C6H6(GT): double, S2(NMHC): int, NOx(GT): int, S3(NOx): int, NO2(GT): int, S4(NO2): int, S5(O3): int, T: double, RH: double, AH: double, Is_in_range: boolean]

We see that there is no modification to the dataframe and the message is raised because the column `Date` is not numric type.

#### Checking summarization methods

First using both arguments for the summarization method.

In [255]:
air_data.get_min_max(column = 'CO(GT)', group = 'Date')

           Date  max_CO(GT)  min_CO(GT)
0      9/2/2004         5.2         0.6
1    12/26/2004         3.8         0.3
2     2/18/2005         4.8         0.4
3    10/10/2004         3.7         0.7
4    10/11/2004         4.8         0.4
..          ...         ...         ...
386   1/23/2005         0.8         0.8
387   6/28/2004         5.6         0.4
388   8/16/2004         2.1         0.3
389  12/20/2004         4.1         0.6
390    3/5/2005         3.2         0.8

[391 rows x 3 columns]

When just one of the arguments is given

In [256]:
air_data.get_min_max(column = 'S2(NMHC)')

   max_S2(NMHC)  min_S2(NMHC)
0          2214           383

Now trying to rise an error

In [257]:
air_data.get_min_max(column = 'Date')

The column Date is not a numeric column

It is seen that the code works how is intended to.

### Reading as a `pd.DataFrame`

We are going to imort the data now as a pandas dataframe, and from that dataframe we are going to create and instance of the class using the `@classmethod` created in the class

In [258]:
pd_air_data = pd.read_csv('Data/air.csv')

In [259]:
f_air_data = Project2_class_YC.SparkDataCheck.createfrom_pandas(spark, pd_air_data)

#### Example for the methods

We are going to check the count for the variable `Date` in the dataframe

In [260]:
f_air_data.get_counts('Date')

          Date  Count
0    3/11/2004     24
1    3/12/2004     24
2    3/10/2004      6
3    3/13/2004     24
4    3/15/2004     24
..         ...    ...
386  3/30/2005     24
387  3/31/2005     24
388   4/3/2005     24
389   4/4/2005     15
390   4/2/2005     24

[391 rows x 2 columns]

This table shows what is the number of measurements per day during the time the digital nose was recording air quality data from the Italian city.

## Part II

In this section, the weekly NFL data is going to be filtered and some summary statistic are going to be calculated using the API pandas on spark, and spark SQL. The objective is to get a deep understanding and practice on the most common and useful tools when dealing with data, including filtering, sorting, cleaning, and manipulating different datasets.

Importing the modules that are necessary.

In [261]:
from pyspark.sql import SparkSession
from pyspark.sql import DataFrame
from pyspark.sql import functions as F
import pandas as pd
import pyspark.pandas as ps

spark = SparkSession.builder.appName('my_app').config("spark.sql.ansi.enabled", "false").getOrCreate()

Now we create a pandas on spark dataframe with the nfl data.

In [262]:
nfl_data = ps.read_csv('Data/weekly_nfl_data.csv', sep = ',')

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_csv`, the default index is attached which can cause additional overhead.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

Checking the first 5 rows of the

In [263]:
nfl_data.head()

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

Now we are going to extract all the column names and the info related to each column.

In [264]:
nfl_data.info()

<class 'pyspark.pandas.frame.DataFrame'>
Index: 128873 entries, 0 to 128872
Data columns (total 53 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   player_id                    128873 non-null  object
 1   player_name                  61493 non-null   object
 2   player_display_name          128870 non-null  object
 3   position                     128801 non-null  object
 4   position_group               128801 non-null  object
 5   headshot_url                 69819 non-null   object
 6   recent_team                  128873 non-null  object
 7   season                       128873 non-null  int32
 8   week                         128873 non-null  int32
 9   season_type                  128873 non-null  object
 10  opponent_team                128873 non-null  object
 11  completions                  128873 non-null  int32
 12  attempts                     128873 non-null  int32
 13  passing_yards                128873 non-null  float64
 14  passing_tds                  128873 non-null  int32
 15  interceptions                128873 non-null  float64
 16  sacks                        128873 non-null  float64
 17  sack_yards                   128873 non-null  float64
 18  sack_fumbles                 128873 non-null  int32
 19  sack_fumbles_lost            128873 non-null  int32
 20  passing_air_yards            128873 non-null  float64
 21  passing_yards_after_catch    128873 non-null  float64
 22  passing_first_downs          128873 non-null  float64
 23  passing_epa                  16467 non-null   float64
 24  passing_2pt_conversions      128873 non-null  int32
 25  pacr                         16027 non-null   float64
 26  dakota                       14460 non-null   float64
 27  carries                      128873 non-null  int32
 28  rushing_yards                128873 non-null  float64
 29  rushing_tds                  128873 non-null  int32
 30  rushing_fumbles              128873 non-null  float64
 31  rushing_fumbles_lost         128873 non-null  float64
 32  rushing_first_downs          128873 non-null  float64
 33  rushing_epa                  53322 non-null   float64
 34  rushing_2pt_conversions      128873 non-null  int32
 35  receptions                   128873 non-null  int32
 36  targets                      128873 non-null  int32
 37  receiving_yards              128873 non-null  float64
 38  receiving_tds                128873 non-null  int32
 39  receiving_fumbles            128873 non-null  float64
 40  receiving_fumbles_lost       128873 non-null  float64
 41  receiving_air_yards          128873 non-null  float64
 42  receiving_yards_after_catch  128873 non-null  float64
 43  receiving_first_downs        128873 non-null  float64
 44  receiving_epa                102549 non-null  float64
 45  receiving_2pt_conversions    128873 non-null  int32
 46  racr                         99764 non-null   float64
 47  target_share                 102549 non-null  float64
 48  air_yards_share              75922 non-null   float64
 49  wopr                         75922 non-null   float64
 50  special_teams_tds            128873 non-null  float64
 51  fantasy_points               128873 non-null  float64
 52  fantasy_points_ppr           128873 non-null  float64
dtypes: float64(29), int32(15), object(9)

26/03/24 19:27:42 WARN AttachDistributedSequenceExec: clean up cached RDD(1409) in AttachDistributedSequenceExec(7351)

### Stats for QB in regular season 2003 to 2023

We are going to take the original data and perform filtering for quarterback `'QB'`, during the regular season between the 2005 and 2023, for combinations of the name of the players and the season (using the `.groupBy()` method), and finally calculating the sum and the mean for eachof the combiantions.

In [265]:
# On the first line the data is being filtered across different columns with the values especified.
# On the next line we select just the columns that we are going to keep after the data has been filteres
# On the next line it has been grouped by two categorical variables that are the name and the year
# On the las line, the function will calculate sum and mean for all the previously grouped variables.
QB_reg = nfl_data.loc[((nfl_data.position == 'QB') & (nfl_data.season_type == 'REG') & (nfl_data.season >= 2005) & (nfl_data.season <= 2023))\
                      ,['player_display_name', 'season', 'week', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'interceptions'] ]\
                    .groupby(['player_display_name', 'season'])\
                    .agg(['sum', 'mean'])

In [266]:
QB_reg.info()

<class 'pyspark.pandas.frame.DataFrame'>
MultiIndex: 1456 entries, (Jake Delhomme, 2006) to (Will Levis, 2023)
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (week, sum)            1456 non-null   int64
 1   (week, mean)           1456 non-null   float64
 2   (completions, sum)     1456 non-null   int64
 3   (completions, mean)    1456 non-null   float64
 4   (attempts, sum)        1456 non-null   int64
 5   (attempts, mean)       1456 non-null   float64
 6   (passing_yards, sum)   1456 non-null   float64
 7   (passing_yards, mean)  1456 non-null   float64
 8   (passing_tds, sum)     1456 non-null   int64
 9   (passing_tds, mean)    1456 non-null   float64
 10  (interceptions, sum)   1456 non-null   float64
 11  (interceptions, mean)  1456 non-null   float64
dtypes: float64(8), int64(4)

In this code chunk two new variables are included where the completion percentage and the ratio of passing to interceptions are calculated and included in a new `ps.DataFrame`

In [267]:
#This line is claculating the completion percentage variable and adding it as a new column to the pandas dataframe.
QB_reg['completion_percentage'] = QB_reg[('completions'), ('sum')] / QB_reg[('attempts'), ('sum')]

#This line is claculating the ratio variable and adding it as a new column to the pandas dataframe.
QB_reg['td_int_ratio'] = QB_reg[('passing_tds'), ('sum')] / QB_reg[('interceptions'), ('sum')]

In [268]:
QB_reg.head()

                           week            completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                            sum       mean         sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Jake Delhomme       2006     99   7.615385         263  20.230769      431  33.153846        2805.0  215.769231          17  1.307692          11.0  0.846154              0.610209     1.545455
Jake Plummer        2005    144   9.000000         277  17.312500      456  28.500000        3366.0  210.375000          18  1.125000           7.0  0.437500              0.607456     2.571429
Matt Schaub         2006     60  12.000000          18   3.600000       27   5.400000         208.0   41.600000           1  0.200000           2.0  0.400000              0.666667     0.500000
Vince Young         2006    143   9.533333         184  12.266667      356  23.733333        2199.0  146.600000          12  0.800000          13.0  0.866667              0.516854     0.923077
Kerry Collins       2007     48   8.000000          50   8.333333       82  13.666667         531.0   88.500000           0  0.000000           0.0  0.000000              0.609756          NaN

### Subsetting the new dataframe

First we are going to filter the values when the sum of attempts is at least 50, and sorted by the completion percentage, showing jus the first 40 rows of the dataframe.

In [269]:
#First it is necessary to filter the data and then a descending sorting is performed based on the completion percentage.
QB_reg.loc[QB_reg[('attempts', 'sum')] >= 50]\
        .sort_values(by = 'completion_percentage', ascending = False).head(40)

                           week            completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                            sum       mean         sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
C.J. Beathard       2023     65  10.833333          40   6.666667       53   8.833333         349.0   58.166667           1  0.166667           0.0  0.000000              0.754717          inf
Colt McCoy          2021     62   8.857143          74  10.571429       99  14.142857         740.0  105.714286           3  0.428571           1.0  0.142857              0.747475     3.000000
Matt Schaub         2019     52  10.400000          50  10.000000       67  13.400000         580.0  116.000000           3  0.600000           1.0  0.200000              0.746269     3.000000
Drew Brees          2018    130   8.666667         364  24.266667      489  32.600000        3992.0  266.133333          32  2.133333           5.0  0.333333              0.744376     6.400000
                    2019    119  10.818182         281  25.545455      378  34.363636        2979.0  270.818182          27  2.454545           4.0  0.363636              0.743386     6.750000
Mason Rudolph       2023     66  16.500000          55  13.750000       74  18.500000         719.0  179.750000           3  0.750000           0.0  0.000000              0.743243          inf
Taysom Hill         2020    147   9.187500          88   5.500000      121   7.562500         928.0   58.000000           4  0.250000           2.0  0.125000              0.727273     2.000000
Nick Foles          2018     51  10.200000         141  28.200000      195  39.000000        1413.0  282.600000           7  1.400000           4.0  0.800000              0.723077     1.750000
Drew Brees          2017    148   9.250000         386  24.125000      536  33.500000        4334.0  270.875000          23  1.437500           8.0  0.500000              0.720149     2.875000
Sam Bradford        2016    146   9.733333         395  26.333333      552  36.800000        3877.0  258.466667          20  1.333333           5.0  0.333333              0.715580     4.000000
Drew Brees          2011    142   8.875000         471  29.437500      660  41.250000        5535.0  345.937500          46  2.875000          14.0  0.875000              0.713636     3.285714
Colt McCoy          2014     57  11.400000          91  18.200000      128  25.600000        1057.0  211.400000           4  0.800000           3.0  0.600000              0.710938     1.333333
Aaron Rodgers       2020    148   9.250000         372  23.250000      526  32.875000        4299.0  268.687500          48  3.000000           5.0  0.312500              0.707224     9.600000
Bailey Zappe        2022     22   5.500000          65  16.250000       92  23.000000         781.0  195.250000           5  1.250000           3.0  0.750000              0.706522     1.666667
Drew Brees          2009    131   8.733333         363  24.200000      514  34.266667        4388.0  292.533333          34  2.266667          11.0  0.733333              0.706226     3.090909
                    2020     97   8.083333         275  22.916667      390  32.500000        2942.0  245.166667          24  2.000000           6.0  0.500000              0.705128     4.000000
Joe Burrow          2021    143   8.937500         366  22.875000      520  32.500000        4611.0  288.187500          34  2.125000          14.0  0.875000              0.703846     2.428571
Derek Carr          2019    147   9.187500         361  22.562500      513  32.062500        4054.0  253.375000          21  1.312500           8.0  0.500000              0.703704     2.625000
Jake Browning       2023    117  13.000000         171  19.000000      243  27.000000        1936.0  215.111111          12  1.333333           7.0  0.777778              0.703704     1.714286
Chase Daniel        2019     20   6.666667          45  15.000000       64  21.333333         435.0  145.000000           3  1.000000           2.0  0.666667              0.703125     1.500000
Ryan Tannehill      2019    128  10.666667         201  16.750000      286  23.833333        2742.0  228.500000          22  1.833333           6.0  0.500000              0.702797     3.666667
Deshaun Watson      2020    145   9.062500         382  23.875000      544  34.000000        4823.0  301.437500          33  2.062500           7.0  0.437500              0.702206     4.714286
Alex Smith          2012     63   6.300000         153  15.300000      218  21.800000        1737.0  173.700000          13  1.300000           5.0  0.500000              0.701835     2.600000
Kirk Cousins        2018    143   8.937500         425  26.562500      606  37.875000        4298.0  268.625000          30  1.875000          10.0  0.625000              0.701320     3.000000
Jamie Martin        2005     92  11.500000         124  15.500000      177  22.125000        1277.0  159.625000           5  0.625000           7.0  0.875000              0.700565     0.714286
Drew Brees          2016    148   9.250000         471  29.437500      673  42.062500        5208.0  325.500000          37  2.312500          15.0  0.937500              0.699851     2.466667
Tony Romo           2014    133   8.866667         304  20.266667      435  29.000000        3705.0  247.000000          34  2.266667           9.0  0.600000              0.698851     3.777778
Matt Ryan           2016    142   8.875000         373  23.312500      534  33.375000        4944.0  309.000000          38  2.375000           7.0  0.437500              0.698502     5.428571
Kirk Cousins        2015    145   9.062500         379  23.687500      543  33.937500        4166.0  260.375000          29  1.812500          11.0  0.687500              0.697974     2.636364
Geno Smith          2022    160   9.411765         399  23.470588      572  33.647059        4282.0  251.882353          30  1.764706          11.0  0.647059              0.697552     2.727273
Chase Daniel        2018     38   9.500000          53  13.250000       76  19.000000         515.0  128.750000           3  0.750000           2.0  0.500000              0.697368     1.500000
Carson Wentz        2018     93   8.454545         279  25.363636      401  36.454545        3074.0  279.454545          21  1.909091           7.0  0.636364              0.695761     3.000000
Dak Prescott        2023    164   9.647059         410  24.117647      590  34.705882        4516.0  265.647059          36  2.117647           9.0  0.529412              0.694915     4.000000
Philip Rivers       2013    145   9.062500         378  23.625000      544  34.000000        4478.0  279.875000          32  2.000000          11.0  0.687500              0.694853     2.909091
Tony Romo           2010     24   4.000000         148  24.666667      213  35.500000        1605.0  267.500000          11  1.833333           7.0  1.166667              0.694836     1.571429
Kirk Cousins        2023     36   4.500000         216  27.000000      311  38.875000        2331.0  291.375000          18  2.250000           5.0  0.625000              0.694534     3.600000
Matt Ryan           2018    145   9.062500         422  26.375000      608  38.000000        4924.0  307.750000          35  2.187500           7.0  0.437500              0.694079     5.000000
Brock Purdy         2023    144   9.000000         308  19.250000      444  27.750000        4280.0  267.500000          31  1.937500          11.0  0.687500              0.693694     2.818182
Jim Sorgi           2005     57  11.400000          43   8.600000       62  12.400000         444.0   88.800000           3  0.600000           1.0  0.200000              0.693548     3.000000
Brandon Weeden      2015     45   7.500000          97  16.166667      140  23.333333        1043.0  173.833333           5  0.833333           2.0  0.333333              0.692857     2.500000

Now we are going to get the values sorted by the `td_int_ratio` and show just the first 40 rows.

In [270]:
#Now the same filtering, but with the sorting based on the ratio variable.
QB_reg.loc[QB_reg[('attempts', 'sum')] >= 50]\
        .sort_values(by = 'td_int_ratio', ascending = False).head(40)

                           week            completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                            sum       mean         sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Charlie Batch       2006     71  10.142857          30   4.285714       52   7.428571         477.0   68.142857           5  0.714286           0.0  0.000000              0.576923          inf
Matt Schaub         2005     65   9.285714          33   4.714286       64   9.142857         495.0   70.714286           4  0.571429           0.0  0.000000              0.515625          inf
Todd Collins        2007     62  15.500000          67  16.750000      105  26.250000         888.0  222.000000           5  1.250000           0.0  0.000000              0.638095          inf
Troy Smith          2007     62  15.500000          40  10.000000       76  19.000000         452.0  113.000000           2  0.500000           0.0  0.000000              0.526316          inf
Jake Locker         2011     51  10.200000          34   6.800000       66  13.200000         542.0  108.400000           4  0.800000           0.0  0.000000              0.515152          inf
Brian Hoyer         2016     27   4.500000         134  22.333333      200  33.333333        1445.0  240.833333           6  1.000000           0.0  0.000000              0.670000          inf
Nick Foles          2016     17   8.500000          36  18.000000       55  27.500000         410.0  205.000000           3  1.500000           0.0  0.000000              0.654545          inf
Derek Anderson      2014     30   6.000000          65  13.000000       97  19.400000         701.0  140.200000           5  1.000000           0.0  0.000000              0.670103          inf
Jimmy Garoppolo     2016     49   8.166667          43   7.166667       63  10.500000         502.0   83.666667           4  0.666667           0.0  0.000000              0.682540          inf
Matt Moore          2019     54   9.000000          59   9.833333       91  15.166667         659.0  109.833333           4  0.666667           0.0  0.000000              0.648352          inf
C.J. Beathard       2020     67  11.166667          66  11.000000      104  17.333333         787.0  131.166667           6  1.000000           0.0  0.000000              0.634615          inf
Andy Dalton         2023      8   4.000000          34  17.000000       58  29.000000         361.0  180.500000           2  1.000000           0.0  0.000000              0.586207          inf
Mason Rudolph       2023     66  16.500000          55  13.750000       74  18.500000         719.0  179.750000           3  0.750000           0.0  0.000000              0.743243          inf
Desmond Ridder      2022     66  16.500000          73  18.250000      115  28.750000         708.0  177.000000           2  0.500000           0.0  0.000000              0.634783          inf
C.J. Beathard       2023     65  10.833333          40   6.666667       53   8.833333         349.0   58.166667           1  0.166667           0.0  0.000000              0.754717          inf
Tom Brady           2016    134  11.166667         291  24.250000      432  36.000000        3554.0  296.166667          28  2.333333           2.0  0.166667              0.673611    14.000000
Nick Foles          2013    129   9.923077         203  15.615385      317  24.384615        2891.0  222.384615          27  2.076923           2.0  0.153846              0.640379    13.500000
Josh McCown         2013     92  11.500000         149  18.625000      224  28.000000        1829.0  228.625000          13  1.625000           1.0  0.125000              0.665179    13.000000
Aaron Rodgers       2018    146   9.125000         372  23.250000      597  37.312500        4442.0  277.625000          25  1.562500           2.0  0.125000              0.623116    12.500000
Damon Huard         2006     69   6.900000         148  14.800000      244  24.400000        1878.0  187.800000          11  1.100000           1.0  0.100000              0.606557    11.000000
Aaron Rodgers       2020    148   9.250000         372  23.250000      526  32.875000        4299.0  268.687500          48  3.000000           5.0  0.312500              0.707224     9.600000
                    2021    149   9.312500         366  22.875000      531  33.187500        4115.0  257.187500          37  2.312500           4.0  0.250000              0.689266     9.250000
Tom Brady           2010    148   9.250000         324  20.250000      492  30.750000        3900.0  243.750000          36  2.250000           4.0  0.250000              0.658537     9.000000
Jake Delhomme       2007      6   2.000000          55  18.333333       86  28.666667         617.0  205.666667           8  2.666667           1.0  0.333333              0.639535     8.000000
Aaron Rodgers       2014    144   9.000000         341  21.312500      520  32.500000        4381.0  273.812500          38  2.375000           5.0  0.312500              0.655769     7.600000
                    2011    128   8.533333         342  22.800000      501  33.400000        4636.0  309.066667          45  3.000000           6.0  0.400000              0.682635     7.500000
Drew Brees          2019    119  10.818182         281  25.545455      378  34.363636        2979.0  270.818182          27  2.454545           4.0  0.363636              0.743386     6.750000
Aaron Rodgers       2019    142   8.875000         353  22.062500      569  35.562500        4002.0  250.125000          26  1.625000           4.0  0.250000              0.620387     6.500000
Drew Brees          2018    130   8.666667         364  24.266667      489  32.600000        3992.0  266.133333          32  2.133333           5.0  0.333333              0.744376     6.400000
Patrick Mahomes     2020    126   8.400000         390  26.000000      588  39.200000        4740.0  316.000000          38  2.533333           6.0  0.400000              0.663265     6.333333
Tom Brady           2007    143   8.937500         398  24.875000      578  36.125000        4806.0  300.375000          50  3.125000           8.0  0.500000              0.688581     6.250000
Russell Wilson      2019    142   8.875000         341  21.312500      516  32.250000        4110.0  256.875000          31  1.937500           5.0  0.312500              0.660853     6.200000
David Garrard       2007    105   8.750000         208  17.333333      325  27.083333        2509.0  209.083333          18  1.500000           3.0  0.250000              0.640000     6.000000
Matthew Stafford    2010     26   6.500000          57  14.250000       96  24.000000         535.0  133.750000           6  1.500000           1.0  0.250000              0.593750     6.000000
Lamar Jackson       2019    128   8.533333         265  17.666667      401  26.733333        3127.0  208.466667          36  2.400000           6.0  0.400000              0.660848     6.000000
Dak Prescott        2016    146   9.125000         311  19.437500      459  28.687500        3667.0  229.187500          23  1.437500           4.0  0.250000              0.677560     5.750000
Aaron Rodgers       2016    149   9.312500         401  25.062500      610  38.125000        4428.0  276.750000          40  2.500000           7.0  0.437500              0.657377     5.714286
Peyton Manning      2013    144   9.000000         450  28.125000      659  41.187500        5477.0  342.312500          55  3.437500          10.0  0.625000              0.682853     5.500000
Matt Ryan           2016    142   8.875000         373  23.312500      534  33.375000        4944.0  309.000000          38  2.375000           7.0  0.437500              0.698502     5.428571
Alex Smith          2017    126   8.400000         341  22.733333      505  33.666667        4042.0  269.466667          26  1.733333           5.0  0.333333              0.675248     5.200000

It can be seen that as some of the sum of interceptions is 0, the first set of vlaues for the ratio yields the value `inf`.

### The same now with `Spark SQL DataFrame`

We start by importing the data as a Spark SQL DataFrame.

In [271]:
#We import the data as a spark SQL DataFrame
nfld_spark = spark.read.load('Data/weekly_nfl_data.csv',
                            format = 'csv',
                            sep = ',',
                            inferSchema = 'true',
                            header = 'true')

Then we get the first 5 rows using the method `.show()` on the dataframe,.

In [272]:
nfld_spark.show(3)

+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
| player_id|player_name| player_display_name|position|position_group|headshot_url|recent_team|season|week|season_type|opponent_team|completions|attempts|passing_yards|passing_tds|interceptions|sacks|sack_yards|sack_fumbles|sack_fumbles_lost|passing_air_yards|passing_yards_after_catch|passing_first_downs|passing_epa|passing_2pt_conversions|pacr|dakota|carries|rushing_yards|rushing_tds|rushing_fumbles|rushing_fumbles_lost|rushing_first_downs|rushing_epa|rushing_2pt_conversions|receptions|targets|receiving_yards|receiving_tds|receiving_fumbles|receiving_fumbles_lost|receiving_air_yards|receiving_yards_after_catch|receiving_first_downs|receiving_epa|receiving_2pt_conversions|racr|target_share|air_yards_share|wopr|special_teams_tds|fantasy_points|fantasy_points_ppr|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   1|        REG|          DEN|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     16|         60.0|          1|            0.0|                 0.0|                4.0|   6.248771|                      0|         1|      1|            7.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|   0.29237816|                        0| 0.0|  0.05263158|           NULL|NULL|              0.0|          12.7|              13.7|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   2|        REG|          ARI|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      9|         33.0|          0|            0.0|                 0.0|                1.0| -1.4349501|                      0|         3|      4|           18.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  1.0|    0.3770089|                        0| 0.0|  0.11764706|           NULL|NULL|              0.0|           5.1|               8.1|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   4|        REG|          BUF|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      3|          2.0|          0|            0.0|                 0.0|                0.0| -1.5399517|                      0|         0|      1|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.69957775|                        0|NULL| 0.023809524|           NULL|NULL|              0.0|           0.2|               0.2|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
only showing top 3 rows

Then we report all the column names.

In [273]:
nfld_spark.columns

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

#### Subsetting on Spark SQL

We are going to take the original data and perform filtering for quarterback `'QB'`, during the regular season between the 2005 and 2023, for combinations of the name of the players and the season (using the `.groupBy()` method), and finally calculating the sum and the mean for each of the combiantions.

In [274]:
# On the first line, we select just the columns that we are going to keep after the data has been filteres
# On the next three lines, the data is being filtered across different columns with the values especified.
# On the las line, the data is being grouped.
QB_reg2 = nfld_spark.select(['player_display_name', 'season', 'week', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'interceptions'])\
                    .where(nfld_spark.position == 'QB')\
                    .where(nfld_spark.season_type == 'REG')\
                    .where((nfld_spark.season >=2005) & (nfld_spark.season <=2023))\
                    .groupBy(['player_display_name', 'season'])

After a grouped object has been generated to make this process easy, two tables are going to be claculated and join in the column of the player name, dropping the columns that do not make sense to calculate statistics (`week` and `season`)

In [275]:
QB_reg2.sum().show(10)

+-------------------+------+-----------+---------+----------------+-------------+------------------+----------------+------------------+
|player_display_name|season|sum(season)|sum(week)|sum(completions)|sum(attempts)|sum(passing_yards)|sum(passing_tds)|sum(interceptions)|
+-------------------+------+-----------+---------+----------------+-------------+------------------+----------------+------------------+
|      Jake Delhomme|  2006|      26078|       99|             263|          431|            2805.0|              17|              11.0|
|       Jake Plummer|  2005|      32080|      144|             277|          456|            3366.0|              18|               7.0|
|        Matt Schaub|  2006|      10030|       60|              18|           27|             208.0|               1|               2.0|
|        Vince Young|  2006|      30090|      143|             184|          356|            2199.0|              12|              13.0|
|      Kerry Collins|  2007|      12042|       48|              50|           82|             531.0|               0|               0.0|
|       Todd Collins|  2005|       2005|       11|               0|            0|               0.0|               0|               0.0|
|      Charlie Batch|  2006|      14042|       71|              30|           52|             477.0|               5|               0.0|
|        Eli Manning|  2006|      32096|      149|             301|          522|            3244.0|              25|              18.0|
|        A.J. Feeley|  2006|       4012|       29|              26|           38|             342.0|               3|               0.0|
|       Mark Brunell|  2006|      20060|       64|             162|          261|            1789.0|               8|               4.0|
+-------------------+------+-----------+---------+----------------+-------------+------------------+----------------+------------------+
only showing top 10 rows

In [276]:
#The result of aggregating the variables by sum is going to be join with the result of aggregating the variables by mean on the two variables of interest.
QB_reg2 = QB_reg2.sum()\
                 .join(QB_reg2.mean(), on = ['player_display_name', 'season'])\
                 .drop('avg(week)', 'avg(season)', 'sum(week)', 'sum(season)') 
#Four variables that do not make sense to calculate sum and mean are dropped.
QB_reg2.show(3)

+-------------------+------+----------------+-------------+------------------+----------------+------------------+-----------------+-----------------+------------------+------------------+------------------+
|player_display_name|season|sum(completions)|sum(attempts)|sum(passing_yards)|sum(passing_tds)|sum(interceptions)| avg(completions)|    avg(attempts)|avg(passing_yards)|  avg(passing_tds)|avg(interceptions)|
+-------------------+------+----------------+-------------+------------------+----------------+------------------+-----------------+-----------------+------------------+------------------+------------------+
|      Jake Delhomme|  2006|             263|          431|            2805.0|              17|              11.0|20.23076923076923|33.15384615384615|215.76923076923077|1.3076923076923077|0.8461538461538461|
|       Jake Plummer|  2005|             277|          456|            3366.0|              18|               7.0|          17.3125|             28.5|           210.375|             1.125|            0.4375|
|        Matt Schaub|  2006|              18|           27|             208.0|               1|               2.0|              3.6|              5.4|              41.6|               0.2|               0.4|
+-------------------+------+----------------+-------------+------------------+----------------+------------------+-----------------+-----------------+------------------+------------------+------------------+
only showing top 3 rows

Now we are going to calculate some other parameters that important to know the performance of the players.

In [277]:
#Creating the two new variables of performance for each of the players per year, passing them as a dictionary.
QB_reg2 = QB_reg2.withColumns({'completion_percentage': QB_reg2['sum(completions)'] / QB_reg2['sum(attempts)'], \
                               'td_int_ratio': QB_reg2['sum(passing_tds)'] / QB_reg2['sum(interceptions)']})

In [278]:
QB_reg2.show(3)

+-------------------+------+----------------+-------------+------------------+----------------+------------------+-----------------+-----------------+------------------+------------------+------------------+---------------------+------------------+
|player_display_name|season|sum(completions)|sum(attempts)|sum(passing_yards)|sum(passing_tds)|sum(interceptions)| avg(completions)|    avg(attempts)|avg(passing_yards)|  avg(passing_tds)|avg(interceptions)|completion_percentage|      td_int_ratio|
+-------------------+------+----------------+-------------+------------------+----------------+------------------+-----------------+-----------------+------------------+------------------+------------------+---------------------+------------------+
|      Jake Delhomme|  2006|             263|          431|            2805.0|              17|              11.0|20.23076923076923|33.15384615384615|215.76923076923077|1.3076923076923077|0.8461538461538461|   0.6102088167053364|1.5454545454545454|
|       Jake Plummer|  2005|             277|          456|            3366.0|              18|               7.0|          17.3125|             28.5|           210.375|             1.125|            0.4375|   0.6074561403508771|2.5714285714285716|
|        Matt Schaub|  2006|              18|           27|             208.0|               1|               2.0|              3.6|              5.4|              41.6|               0.2|               0.4|   0.6666666666666666|               0.5|
+-------------------+------+----------------+-------------+------------------+----------------+------------------+-----------------+-----------------+------------------+------------------+------------------+---------------------+------------------+
only showing top 3 rows

After the columns have been created now we filter the values where the sum of attempts is larger or equal to 50, then the values are going to be sorted based on completion percentage.

In [279]:
#First the new dataset is being filtered for the players with a larger or equal to 50 total attempts.
QB_reg2 = QB_reg2.filter(QB_reg2['sum(attempts)'] >= 50)

Showing the first 40 rows

In [280]:
#The data has been sorted descending and to get a better viasualization of the data, the data set is being converted to a Pandas Dataframe
QB_reg2.sort(QB_reg2['completion_percentage'], ascending = False).toPandas().head(40)

,player_display_name,season,sum(completions),sum(attempts),sum(passing_yards),sum(passing_tds),sum(interceptions),avg(completions),avg(attempts),avg(passing_yards),avg(passing_tds),avg(interceptions),completion_percentage,td_int_ratio
0,C.J. Beathard,2023,40,53,349.0,1,0.0,6.666667,8.833333,58.166667,0.166667,0.000000,0.754717,NaN
1,Colt McCoy,2021,74,99,740.0,3,1.0,10.571429,14.142857,105.714286,0.428571,0.142857,0.747475,3.000000
2,Matt Schaub,2019,50,67,580.0,3,1.0,10.000000,13.400000,116.000000,0.600000,0.200000,0.746269,3.000000
3,Drew Brees,2018,364,489,3992.0,32,5.0,24.266667,32.600000,266.133333,2.133333,0.333333,0.744376,6.400000
4,Drew Brees,2019,281,378,2979.0,27,4.0,25.545455,34.363636,270.818182,2.454545,0.363636,0.743386,6.750000
5,Mason Rudolph,2023,55,74,719.0,3,0.0,13.750000,18.500000,179.750000,0.750000,0.000000,0.743243,NaN
6,Taysom Hill,2020,88,121,928.0,4,2.0,5.500000,7.562500,58.000000,0.250000,0.125000,0.727273,2.000000
7,Nick Foles,2018,141,195,1413.0,7,4.0,28.200000,39.000000,282.600000,1.400000,0.800000,0.723077,1.750000
8,Drew Brees,2017,386,536,4334.0,23,8.0,24.125000,33.500000,270.875000,1.437500,0.500000,0.720149,2.875000
9,Sam Bradford,2016,395,552,3877.0,20,5.0,26.333333,36.800000,258.466667,1.333333,0.333333,0.715580,4.000000
10,Drew Brees,2011,471,660,5535.0,46,14.0,29.437500,41.250000,345.937500,2.875000,0.875000,0.713636,3.285714
11,Colt McCoy,2014,91,128,1057.0,4,3.0,18.200000,25.600000,211.400000,0.800000,0.600000,0.710938,1.333333
12,Aaron Rodgers,2020,372,526,4299.0,48,5.0,23.250000,32.875000,268.687500,3.000000,0.312500,0.707224,9.600000
13,Bailey Zappe,2022,65,92,781.0,5,3.0,16.250000,23.000000,195.250000,1.250000,0.750000,0.706522,1.666667
14,Drew Brees,2009,363,514,4388.0,34,11.0,24.200000,34.266667,292.533333,2.266667,0.733333,0.706226,3.090909
15,Drew Brees,2020,275,390,2942.0,24,6.0,22.916667,32.500000,245.166667,2.000000,0.500000,0.705128,4.000000
16,Joe Burrow,2021,366,520,4611.0,34,14.0,22.875000,32.500000,288.187500,2.125000,0.875000,0.703846,2.428571
17,Derek Carr,2019,361,513,4054.0,21,8.0,22.562500,32.062500,253.375000,1.312500,0.500000,0.703704,2.625000
18,Jake Browning,2023,171,243,1936.0,12,7.0,19.000000,27.000000,215.111111,1.333333,0.777778,0.703704,1.714286
19,Chase Daniel,2019,45,64,435.0,3,2.0,15.000000,21.333333,145.000000,1.000000,0.666667,0.703125,1.500000
20,Ryan Tannehill,2019,201,286,2742.0,22,6.0,16.750000,23.833333,228.500000,1.833333,0.500000,0.702797,3.666667
21,Deshaun Watson,2020,382,544,4823.0,33,7.0,23.875000,34.000000,301.437500,2.062500,0.437500,0.702206,4.714286
22,Alex Smith,2012,153,218,1737.0,13,5.0,15.300000,21.800000,173.700000,1.300000,0.500000,0.701835,2.600000
23,Kirk Cousins,2018,425,606,4298.0,30,10.0,26.562500,37.875000,268.625000,1.875000,0.625000,0.701320,3.000000
24,Jamie Martin,2005,124,177,1277.0,5,7.0,15.500000,22.125000,159.625000,0.625000,0.875000,0.700565,0.714286
25,Drew Brees,2016,471,673,5208.0,37,15.0,29.437500,42.062500,325.500000,2.312500,0.937500,0.699851,2.466667
26,Tony Romo,2014,304,435,3705.0,34,9.0,20.266667,29.000000,247.000000,2.266667,0.600000,0.698851,3.777778
27,Matt Ryan,2016,373,534,4944.0,38,7.0,23.312500,33.375000,309.000000,2.375000,0.437500,0.698502,5.428571
28,Kirk Cousins,2015,379,543,4166.0,29,11.0,23.687500,33.937500,260.375000,1.812500,0.687500,0.697974,2.636364
29,Geno Smith,2022,399,572,4282.0,30,11.0,23.470588,33.647059,251.882353,1.764706,0.647059,0.697552,2.727273
30,Chase Daniel,2018,53,76,515.0,3,2.0,13.250000,19.000000,128.750000,0.750000,0.500000,0.697368,1.500000
31,Carson Wentz,2018,279,401,3074.0,21,7.0,25.363636,36.454545,279.454545,1.909091,0.636364,0.695761,3.000000
32,Dak Prescott,2023,410,590,4516.0,36,9.0,24.117647,34.705882,265.647059,2.117647,0.529412,0.694915,4.000000
33,Philip Rivers,2013,378,544,4478.0,32,11.0,23.625000,34.000000,279.875000,2.000000,0.687500,0.694853,2.909091
34,Tony Romo,2010,148,213,1605.0,11,7.0,24.666667,35.500000,267.500000,1.833333,1.166667,0.694836,1.571429
35,Kirk Cousins,2023,216,311,2331.0,18,5.0,27.000000,38.875000,291.375000,2.250000,0.625000,0.694534,3.600000
36,Matt Ryan,2018,422,608,4924.0,35,7.0,26.375000,38.000000,307.750000,2.187500,0.437500,0.694079,5.000000
37,Brock Purdy,2023,308,444,4280.0,31,11.0,19.250000,27.750000,267.500000,1.937500,0.687500,0.693694,2.818182
38,Jim Sorgi,2005,43,62,444.0,3,1.0,8.600000,12.400000,88.800000,0.600000,0.200000,0.693548,3.000000
39,Brandon Weeden,2015,97,140,1043.0,5,2.0,16.166667,23.333333,173.833333,0.833333,0.333333,0.692857,2.500000

Now we sort by the `td_int_ratio`

In [281]:
#The process is the same, just sorting by a different variable.
QB_reg2.sort(QB_reg2['td_int_ratio'], ascending = False).toPandas().head(40)

,player_display_name,season,sum(completions),sum(attempts),sum(passing_yards),sum(passing_tds),sum(interceptions),avg(completions),avg(attempts),avg(passing_yards),avg(passing_tds),avg(interceptions),completion_percentage,td_int_ratio
0,Tom Brady,2016,291,432,3554.0,28,2.0,24.250000,36.000000,296.166667,2.333333,0.166667,0.673611,14.000000
1,Nick Foles,2013,203,317,2891.0,27,2.0,15.615385,24.384615,222.384615,2.076923,0.153846,0.640379,13.500000
2,Josh McCown,2013,149,224,1829.0,13,1.0,18.625000,28.000000,228.625000,1.625000,0.125000,0.665179,13.000000
3,Aaron Rodgers,2018,372,597,4442.0,25,2.0,23.250000,37.312500,277.625000,1.562500,0.125000,0.623116,12.500000
4,Damon Huard,2006,148,244,1878.0,11,1.0,14.800000,24.400000,187.800000,1.100000,0.100000,0.606557,11.000000
5,Aaron Rodgers,2020,372,526,4299.0,48,5.0,23.250000,32.875000,268.687500,3.000000,0.312500,0.707224,9.600000
6,Aaron Rodgers,2021,366,531,4115.0,37,4.0,22.875000,33.187500,257.187500,2.312500,0.250000,0.689266,9.250000
7,Tom Brady,2010,324,492,3900.0,36,4.0,20.250000,30.750000,243.750000,2.250000,0.250000,0.658537,9.000000
8,Jake Delhomme,2007,55,86,617.0,8,1.0,18.333333,28.666667,205.666667,2.666667,0.333333,0.639535,8.000000
9,Aaron Rodgers,2014,341,520,4381.0,38,5.0,21.312500,32.500000,273.812500,2.375000,0.312500,0.655769,7.600000
10,Aaron Rodgers,2011,342,501,4636.0,45,6.0,22.800000,33.400000,309.066667,3.000000,0.400000,0.682635,7.500000
11,Drew Brees,2019,281,378,2979.0,27,4.0,25.545455,34.363636,270.818182,2.454545,0.363636,0.743386,6.750000
12,Aaron Rodgers,2019,353,569,4002.0,26,4.0,22.062500,35.562500,250.125000,1.625000,0.250000,0.620387,6.500000
13,Drew Brees,2018,364,489,3992.0,32,5.0,24.266667,32.600000,266.133333,2.133333,0.333333,0.744376,6.400000
14,Patrick Mahomes,2020,390,588,4740.0,38,6.0,26.000000,39.200000,316.000000,2.533333,0.400000,0.663265,6.333333
15,Tom Brady,2007,398,578,4806.0,50,8.0,24.875000,36.125000,300.375000,3.125000,0.500000,0.688581,6.250000
16,Russell Wilson,2019,341,516,4110.0,31,5.0,21.312500,32.250000,256.875000,1.937500,0.312500,0.660853,6.200000
17,Lamar Jackson,2019,265,401,3127.0,36,6.0,17.666667,26.733333,208.466667,2.400000,0.400000,0.660848,6.000000
18,David Garrard,2007,208,325,2509.0,18,3.0,17.333333,27.083333,209.083333,1.500000,0.250000,0.640000,6.000000
19,Matthew Stafford,2010,57,96,535.0,6,1.0,14.250000,24.000000,133.750000,1.500000,0.250000,0.593750,6.000000
20,Dak Prescott,2016,311,459,3667.0,23,4.0,19.437500,28.687500,229.187500,1.437500,0.250000,0.677560,5.750000
21,Aaron Rodgers,2016,401,610,4428.0,40,7.0,25.062500,38.125000,276.750000,2.500000,0.437500,0.657377,5.714286
22,Peyton Manning,2013,450,659,5477.0,55,10.0,28.125000,41.187500,342.312500,3.437500,0.625000,0.682853,5.500000
23,Matt Ryan,2016,373,534,4944.0,38,7.0,23.312500,33.375000,309.000000,2.375000,0.437500,0.698502,5.428571
24,Alex Smith,2017,341,505,4042.0,26,5.0,22.733333,33.666667,269.466667,1.733333,0.333333,0.675248,5.200000
25,Patrick Mahomes,2019,319,484,4031.0,26,5.0,22.785714,34.571429,287.928571,1.857143,0.357143,0.659091,5.200000
26,Tom Brady,2015,402,624,4770.0,36,7.0,25.125000,39.000000,298.125000,2.250000,0.437500,0.644231,5.142857
27,Jeff Garcia,2006,116,188,1309.0,10,2.0,14.500000,23.500000,163.625000,1.250000,0.250000,0.617021,5.000000
28,Matt Ryan,2018,422,608,4924.0,35,7.0,26.375000,38.000000,307.750000,2.187500,0.437500,0.694079,5.000000
29,Russell Wilson,2018,280,427,3448.0,35,7.0,17.500000,26.687500,215.500000,2.187500,0.437500,0.655738,5.000000
30,Geno Smith,2021,65,95,702.0,5,1.0,16.250000,23.750000,175.500000,1.250000,0.250000,0.684211,5.000000
31,Aaron Rodgers,2012,371,552,4295.0,39,8.0,23.187500,34.500000,268.437500,2.437500,0.500000,0.672101,4.875000
32,Ryan Tannehill,2020,315,481,3819.0,34,7.0,19.687500,30.062500,238.687500,2.125000,0.437500,0.654886,4.857143
33,Brett Favre,2009,364,532,4202.0,33,7.0,22.750000,33.250000,262.625000,2.062500,0.437500,0.684211,4.714286
34,Carson Wentz,2017,265,440,3296.0,33,7.0,20.384615,33.846154,253.538462,2.538462,0.538462,0.602273,4.714286
35,Deshaun Watson,2020,382,544,4823.0,33,7.0,23.875000,34.000000,301.437500,2.062500,0.437500,0.702206,4.714286
36,Kirk Cousins,2021,372,561,4221.0,33,7.0,23.250000,35.062500,263.812500,2.062500,0.437500,0.663102,4.714286
37,Derek Carr,2016,357,560,3937.0,28,6.0,23.800000,37.333333,262.466667,1.866667,0.400000,0.637500,4.666667
38,Jameis Winston,2021,95,161,1170.0,14,3.0,13.571429,23.000000,167.142857,2.000000,0.428571,0.590062,4.666667
39,C.J. Stroud,2023,319,499,4108.0,23,5.0,21.266667,33.266667,273.866667,1.533333,0.333333,0.639279,4.600000

It is noted that the names for the table where the ratio of passing to interceptions does not match with the one generated only through pandas-on-spark, and this is because spark SQL handle infinite numbers as null values, while pandas handle those values as a inf, which are generated when a number is divided by 0.